# Copyright (C) 2002-2025 Free Software Foundation, Inc.
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <https://www.gnu.org/licenses/>.
#
# As a special exception to the GNU General Public License,
# this file may be distributed as part of a program that
# contains a configuration script generated by Autoconf, under
# the same distribution terms as the rest of that program.
#
# Generated by gnulib-tool.
#
# This file represents the specification of how gnulib-tool is used.
# It acts as a cache: It is written and read by gnulib-tool.
# In projects that use version control, this file is meant to be put under
# version control, like the configure.ac and various Makefile.am files.


# Specification in the form of a command-line invocation:
# gnulib-tool --import \
#  --local-dir=gnulib-local \
#  --lib=libtestsgnu \
#  --source-base=tests/gnulib-lib \
#  --m4-base=tests/gnulib-m4 \
#  --doc-base=doc \
#  --tests-base=tests \
#  --aux-dir=../build-aux \
#  --makefile-name=Makefile.gnulib \
#  --no-conditional-dependencies \
#  --no-libtool \
#  --macro-prefix=gttgl \
#  --avoid=alloca-opt \
#  --avoid=atexit \
#  --avoid=attribute \
#  --avoid=backupfile \
#  --avoid=basename-lgpl \
#  --avoid=bcp47 \
#  --avoid=binary-io \
#  --avoid=bison \
#  --avoid=bison-i18n \
#  --avoid=bool \
#  --avoid=byteswap \
#  --avoid=c-ctype \
#  --avoid=c-strcase \
#  --avoid=c-strcasestr \
#  --avoid=c-strstr \
#  --avoid=clean-temp \
#  --avoid=closedir \
#  --avoid=closeout \
#  --avoid=copy-file \
#  --avoid=csharpcomp \
#  --avoid=csharpexec \
#  --avoid=cygpath \
#  --avoid=error \
#  --avoid=error-progname \
#  --avoid=execute \
#  --avoid=filename \
#  --avoid=findprog \
#  --avoid=flexmember \
#  --avoid=fnmatch \
#  --avoid=fopen \
#  --avoid=free-posix \
#  --avoid=fstrcmp \
#  --avoid=full-write \
#  --avoid=fwriteerror \
#  --avoid=gcd \
#  --avoid=getaddrinfo \
#  --avoid=getline \
#  --avoid=getopt-gnu \
#  --avoid=gettext-h \
#  --avoid=iconv \
#  --avoid=javacomp \
#  --avoid=javaexec \
#  --avoid=libunistring-optional \
#  --avoid=libxml \
#  --avoid=localcharset \
#  --avoid=locale-h \
#  --avoid=localename \
#  --avoid=localtime \
#  --avoid=lock \
#  --avoid=mem-hash-map \
#  --avoid=memchr \
#  --avoid=memmove \
#  --avoid=memset \
#  --avoid=minmax \
#  --avoid=mkdir \
#  --avoid=noreturn \
#  --avoid=obstack \
#  --avoid=open \
#  --avoid=opendir \
#  --avoid=openmp-init \
#  --avoid=pipe-filter-ii \
#  --avoid=progname \
#  --avoid=propername \
#  --avoid=read-file \
#  --avoid=readdir \
#  --avoid=relocatable-prog \
#  --avoid=relocatable-script \
#  --avoid=setlocale \
#  --avoid=sf-istream \
#  --avoid=sh-filename \
#  --avoid=sh-quote \
#  --avoid=sigpipe \
#  --avoid=sigprocmask \
#  --avoid=spawn-pipe \
#  --avoid=stdio-h \
#  --avoid=stdlib-h \
#  --avoid=stpcpy \
#  --avoid=stpncpy \
#  --avoid=str_startswith \
#  --avoid=strchrnul \
#  --avoid=strcspn \
#  --avoid=strerror \
#  --avoid=string-desc \
#  --avoid=strnlen \
#  --avoid=strpbrk \
#  --avoid=strtol \
#  --avoid=strtoul \
#  --avoid=supersede \
#  --avoid=sys_select-h \
#  --avoid=sys_stat-h \
#  --avoid=sys_time-h \
#  --avoid=trim \
#  --avoid=unicase/u8-casefold \
#  --avoid=unictype/ctype-space \
#  --avoid=unictype/property-white-space \
#  --avoid=unictype/syntax-java-whitespace \
#  --avoid=unictype/property-xid-start \
#  --avoid=unictype/property-xid-continue \
#  --avoid=unilbrk/ulc-width-linebreaks \
#  --avoid=uniname/uniname \
#  --avoid=uninorm/nfc \
#  --avoid=unistd-h \
#  --avoid=unistr/u8-check \
#  --avoid=unistr/u8-mbtouc \
#  --avoid=unistr/u8-mbtoucr \
#  --avoid=unistr/u8-uctomb \
#  --avoid=unistr/u16-mbtouc \
#  --avoid=uniwidth/width \
#  --avoid=unlocked-io \
#  --avoid=unsetenv \
#  --avoid=vasprintf \
#  --avoid=vc-mtime \
#  --avoid=wait-process \
#  --avoid=write \
#  --avoid=xalloc \
#  --avoid=xconcat-filename \
#  --avoid=xerror \
#  --avoid=xmalloca \
#  --avoid=xmemdup0 \
#  --avoid=xsetenv \
#  --avoid=xstrerror \
#  --avoid=xstriconv \
#  --avoid=xstriconveh \
#  --avoid=xstring-buffer \
#  --avoid=xstring-desc \
#  --avoid=xvasprintf \
#  --avoid=alloca-opt \
#  --avoid=bool \
#  --avoid=extensions \
#  --avoid=gettext-h \
#  --avoid=include_next \
#  --avoid=locale-h \
#  --avoid=localcharset \
#  --avoid=malloc-posix \
#  --avoid=mbrtowc \
#  --avoid=mbsinit \
#  --avoid=multiarch \
#  --avoid=setlocale-null \
#  --avoid=ssize_t \
#  --avoid=stddef-h \
#  --avoid=stdint-h \
#  --avoid=stdlib-h \
#  --avoid=streq \
#  --avoid=unistd-h \
#  --avoid=verify \
#  --avoid=wchar-h \
#  --avoid=wctype-h \
#  --avoid=windows-mutex \
#  --avoid=windows-once \
#  --avoid=windows-recmutex \
#  --avoid=windows-rwlock \
#  --avoid=gettext-tools-misc \
#  --avoid=ansi-c++-opt \
#  --avoid=csharpcomp-script \
#  --avoid=csharpexec-script \
#  --avoid=java \
#  --avoid=javacomp-script \
#  --avoid=javaexec-script \
#  --avoid=manywarnings \
#  --avoid=stdint-h \
#  --avoid=test-xfail \
#  test-xfail \
#  thread

# Specification in the form of a few gnulib-tool.m4 macro invocations:
gl_LOCAL_DIR([../gnulib-local])
gl_MODULES([
  test-xfail
  thread
])
gl_AVOID([alloca-opt atexit attribute backupfile basename-lgpl bcp47 binary-io bison bison-i18n bool byteswap c-ctype c-strcase c-strcasestr c-strstr clean-temp closedir closeout copy-file csharpcomp csharpexec cygpath error error-progname execute filename findprog flexmember fnmatch fopen free-posix fstrcmp full-write fwriteerror gcd getaddrinfo getline getopt-gnu gettext-h iconv javacomp javaexec libunistring-optional libxml localcharset locale-h localename localtime lock mem-hash-map memchr memmove memset minmax mkdir noreturn obstack open opendir openmp-init pipe-filter-ii progname propername read-file readdir relocatable-prog relocatable-script setlocale sf-istream sh-filename sh-quote sigpipe sigprocmask spawn-pipe stdio-h stdlib-h stpcpy stpncpy str_startswith strchrnul strcspn strerror string-desc strnlen strpbrk strtol strtoul supersede sys_select-h sys_stat-h sys_time-h trim unicase/u8-casefold unictype/ctype-space unictype/property-white-space unictype/syntax-java-whitespace unictype/property-xid-start unictype/property-xid-continue unilbrk/ulc-width-linebreaks uniname/uniname uninorm/nfc unistd-h unistr/u8-check unistr/u8-mbtouc unistr/u8-mbtoucr unistr/u8-uctomb unistr/u16-mbtouc uniwidth/width unlocked-io unsetenv vasprintf vc-mtime wait-process write xalloc xconcat-filename xerror xmalloca xmemdup0 xsetenv xstrerror xstriconv xstriconveh xstring-buffer xstring-desc xvasprintf alloca-opt bool extensions gettext-h include_next locale-h localcharset malloc-posix mbrtowc mbsinit multiarch setlocale-null ssize_t stddef-h stdint-h stdlib-h streq unistd-h verify wchar-h wctype-h windows-mutex windows-once windows-recmutex windows-rwlock gettext-tools-misc ansi-c++-opt csharpcomp-script csharpexec-script java javacomp-script javaexec-script manywarnings stdint-h test-xfail])
gl_SOURCE_BASE([tests/gnulib-lib])
gl_M4_BASE([tests/gnulib-m4])
gl_PO_BASE([])
gl_DOC_BASE([doc])
gl_TESTS_BASE([tests])
gl_LIB([libtestsgnu])
gl_MAKEFILE_NAME([Makefile.gnulib])
gl_MACRO_PREFIX([gttgl])
gl_PO_DOMAIN([])
gl_WITNESS_C_MACRO([])
