//put the defined for all strings into a .h file:
//The strings are not required to be placed in a library result directory.
//- for Windows targets this file shall be included by the .rc file
//- for other targets this file shall be included by the resource string table

//do not use \" here -> MS .rc compiler has problems with that

//todo: separate diaglib and vislib strings

#ifndef DLSTRINGSHPP
#define DLSTRINGSHPP

#include "DLLocalize.hpp" //string indexes

//simple precaution
#ifndef STR_TABLE_INCLUDE
#error STR_TABLE_INCLUDE must be defined before including DLStrings.h
#endif

//just in case we need these guys to be external: (usually for non-Windows targets)
extern const stw::scl::C_SclResourceString gac_DIAG_LIB_RESOURCE_STRINGS[];
extern uint16_t gu16_DIAGLIB_NR_RES_STRNGS;

//Common texts
#define STR_TEXT_ERROR               "Error"
#define STR_TEXT_ERROR_EXCL          "Error !"
#define STR_TEXT_INFO                "Information"
#define STR_TEXT_WARNING             "Warning"
#define STR_TEXT_CONFIRMATION        "Confirmation"
#define STR_TEXT_ERR_NO_NUMBER       "Only numbers allowed"
#define STR_TEXT_FILENAME            "Filename"
#define STR_TEXT_USE_EXISTING        "First use the existing entry."
#define STR_TEXT_VALUE               "Value"
#define STR_TEXT_FILE                "File"
#define STR_TEXT_FILESIZE            "Filesize"
#define STR_TEXT_TIMESTAMP           "Timestamp"
#define STR_TEXT_ERR_FILE_WRITE      "Could not write file"
#define STR_TEXT_ERR_BITRATE_NOT_INT "Bitrate has to be numeric."
#define STR_TEXT_ERR_PROT_WRITE      "Could not write to protocol file"
#define STR_TEXT_ERR_DBS_WRONG       "Data bytes must be >=0 and <=255"
#define STR_TEXT_ERR_NOT_DECIMAL     "Values must be decimal"

//CKFXTraceFile
#define STR_TEXT_TF_ERR_WRITING     "Error writing to trace file."
#define STR_TEXT_TF_ERR_CREATE      "Could not create trace file."
#define STR_TEXT_TF_ERR_APPEND      "Could not append to existing file."

//CPropEditDSList/DSVar
#define STR_TEXT_DS_ERR_NO_DATA_SOURCE "Select a RAM- or EEPROM-DataSource first."
#define STR_TEXT_DS_ERR_NO_VALID_LISTS "No valid lists."

//CPropEditFileName
#define STR_TEXT_FN_FILTER_ALL_FILES   "All Files (*.*)|*.*"

//DlgCMONMain
#define STR_TEXT_CM_TIME_ABSOLUTE   "Time: absolute"
#define STR_TEXT_CM_TIME_RELATIVE   "Time: relative"
#define STR_TEXT_CM_BASE_HEX        "Base: HEX"
#define STR_TEXT_CM_BASE_DEC        "Base: DEC"
#define STR_TEXT_CM_MODE_STATIC     "Mode: static"
#define STR_TEXT_CM_MODE_CONT       "Mode: cont"
#define STR_TEXT_CM_PROT_OFF        "Protocol: off"
#define STR_TEXT_CM_PROT_ON         "Protocol: on"
#define STR_TEXT_CM_L7_NONE         "L7-Protocol: none"
#define STR_TEXT_CM_L7_CAN_OPEN     "L7-Protocol: CANopen"
#define STR_TEXT_CM_L7_KEFEX        "L7-Protocol: KEFEX"
#define STR_TEXT_CM_L7_PPP          "L7-Protocol: STW-PPP"
#define STR_TEXT_CM_ERR_GET_OS_VER  "Could not get OS Version"
#define STR_TEXT_CM_ERR_OS_VER      "Invalid OS Version"
#define STR_TEXT_CM_ERR_L7_PROT_INVALID "Invalid L7 protocol number"
#define STR_TEXT_CM_ERR_NO_DONGLE   "Dongle not found."
#define STR_TEXT_CM_ERR_OPEN_DLL    "Could not open CAN DLL."
#define STR_TEXT_CM_ERR_CLOSE_DLL   "Could not close CAN DLL."
#define STR_TEXT_CM_ERR_INIT_CAN    "Could not init CAN"
#define STR_TEXT_CM_ERR_CAN_STATUS  "Invalid result from CAN_Status."
#define STR_TEXT_CM_CAPTION         "Time    ms.us   Msgs.   ID         L DB0 DB1 DB2 DB3 DB4 DB5 DB6 DB7"
//#define STR_TEXT_CM_CAPTION_PROT    "       Time     Msgs.       ID      DB0 DB1 DB2 DB3 DB4 DB5 DB6 DB7\r\n"
#define STR_TEXT_CM_ERR_PROT_CREATE "Could not create protocol file"
#define STR_TEXT_CM_TX_ERRORS       "TX Errors:"
#define STR_TEXT_CM_CAPTION_KFX_PROT "KEFEX Protocol Parameter"
#define STR_TEXT_CM_PROMPT_KFX_PROT  "Base ID:"
#define STR_TEXT_CM_DLL_INFO_MANUF   "Manufacturer:"
#define STR_TEXT_CM_DLL_INFO_DEVICE  "Device:"
#define STR_TEXT_CM_DLL_INFO_HW_VER  "Hardware version:"
#define STR_TEXT_CM_DLL_INFO_DLL_VER "DLL version:"
#define STR_TEXT_CM_DLL_INFO_XTD     "Extended IDs: supported"
#define STR_TEXT_CM_DLL_INFO_NO_XTD  "Extended IDs: not supported"
#define STR_TEXT_CM_CAPTION_ABOUT    "About KEFEX CMON"

//DlgCMONSend
#define STR_TEXT_CS_ERR_ID_TOO_GREAT   "ID must be <= 0x1FFFFFFF for 29bit IDs"
#define STR_TEXT_CS_ERR_DLC_TOO_GREAT  "DLC must be <= 8"
#define STR_TEXT_CS_ERR_DBS_TOO_GREAT  "DBs must be <= 0xFF"
#define STR_TEXT_CS_ERR_MAX_NUM_MSGS   "Maximum number of messages reached."
#define STR_TEXT_CS_ERR_FILE_READ      "Could not read file"
#define STR_TEXT_CS_ERR_NO_FOCUS       "Set focus to a message first"
#define STR_TEXT_CS_ERR_ID_WRONG       "ID must be numeric and <= 0x1FFFFFFF"
#define STR_TEXT_CS_ERR_DLC_WRONG      "DLC must be numeric and <= 8"
#define STR_TEXT_CS_ERR_DBS_WRONG      "Data bytes must be numeric and <= 255"
#define STR_TEXT_CS_ERR_INTERVAL_WRONG "Interval must be numeric and > 0"
#define STR_TEXT_CS_ERR_OFFSET_WRONG   "Offset must be numeric and > 0"
#define STR_TEXT_CS_ERR_KEY_WRONG      "Trigger key must be one character only"

//DlgKFXComSetup
#define STR_TEXT_CS_ERR_VALUES_NOT_NUMERIC "Parameter is not numeric."
#define STR_TEXT_CS_ERR_INVALID_BASE_ID    "Base ID invalid -> was set to 6"
#define STR_TEXT_CS_ERR_VALUE_RANGE        "Parameter is out of range."

//DlgKFXEditPasswords
#define STR_TEXT_EP_ERR_NO_MATCH       "New password must match confirm password."

//DlgKFXIndexedInputListEditor
#define STR_TEXT_IILE_NO_INTEGER       "Value must be integer."

//DlgKFXIndexedListEditor
#define STR_TEXT_ILE_VALUE_RANGE       "Value Range"
#define STR_TEXT_ILE_VALUE_WRONG       "Value must be numeric or a range (x..y)."

//DlgKFXIndexedStringEditor
#define STR_TEXT_ISE_STRING            "String"
#define STR_TEXT_ISE_VALUE_WRONG       "Value must be numeric."

//DlgRAMEditChart
#define STR_TEXT_REC_LEGEND "Name              Time1    Value1     Time2    Value2     DTime    DValue"
#define STR_TEXT_REC_BUFFER_OVERRUN "Buffer overrun -> Measurement stopped.\nReduce visible points or interval."
#define STR_TEXT_REC_MEASUREMENT_STOPPED "Measurement stopped."
#define STR_TEXT_REC_SERIES              "Series"
#define STR_TEXT_REC_ERR_BUFFER_CREATE "Could not create buffer file !\nNo offline browsing possible."
#define STR_TEXT_REC_ERR_BUFFER_WRITE  "Error writing to buffer."
#define STR_TEXT_REC_ERR_BUFFER_READ   "Error reading from buffer file.\nNo offline browsing possible."
#define STR_TEXT_REC_ERR_NO_VALUES     "There are no values in the list !\n-> Not started."
#define STR_TEXT_REC_ERR_BUFFER_FILE   "Error in buffer file."
#define STR_TEXT_REC_ERR_READ_ONLY     "Read only. Can not be written."
#define STR_TEXT_REC_STATUS_READING    "Reading file ..."
#define STR_TEXT_REC_STATUS_UPDATING   "Updating chart ..."
#define STR_TEXT_REC_MAX_NUM_POINTS    "Maximum number of visible points:"
#define STR_TEXT_REC_WRITTEN           "Written..."
#define STR_TEXT_REC_VARIABLE          "Variable"
#define STR_TEXT_REC_DEVICE            "Device"
#define STR_TEXT_REC_DATE              "Date"
#define STR_TEXT_REC_SENT_TO_PRINTER   "Chart sent to printer ..."
#define STR_TEXT_REC_COPIED_TO_CLIP    "Chart copied to clipboard ..."
#define STR_TEXT_REC_STOP_TRACE        "Stop trace first."

//DlgXFLBBBStream
#define STR_TEXT_FB_STW_PASSWD_OK      "STW password acknowledged."
#define STR_TEXT_FB_CUST_PASSWD_OK     "Customer password acknowledged."
#define STR_TEXT_FB_THANKS             "Thanks"
#define STR_TEXT_FB_WRONG_PASSWD       "Sorry, wrong password."

//DlgXFLMain
//Statusmemo messages
//not 100% comprehensive (e.g. no "0" permitted; no "7..9" for 3 char-CID; but close enough to help the user without
//confusing him/her too much
#define STR_TEXT_FM_ERR_COMP_ID_LENGTH "Error: Company ID not valid (must be 2,3 or 5 upper case letters or digits)."

#define STR_TEXT_FM_ERR_WAKEUP_FAILED  "Error: Wakeup failed"
//#define STR_TEXT_FM_ERR_SNR_FORMAT     "Error: SNR must be in the format: 00.112233.4455."
#define STR_TEXT_FM_ERR_NODE_NOT_FOUND "Error: Node not found"
#define STR_TEXT_FM_ERR_DLL            "Error: Could not init communication DLL (missing or invalid)."
#define STR_TEXT_FM_ERR_OPEN_CAN       "Error: Could not init communication interface."
//#define STR_TEXT_FM_ERR_DLL_NOT_FOUND  "Error: Communication driver DLL not found"
#define STR_TEXT_FM_ERR_LOCALID        "Error: Local ID (no response from node)."
#define STR_TEXT_FM_ERR_COMPANYID      "Error: Company ID."
#define STR_TEXT_FM_ERR_SNR            "Error: SNR."
#define STR_TEXT_FM_ERR_WAKEUP         "Error: Could not wake up node"
//#define STR_TEXT_FM_ERR_DIVERT_STREAM_OFF  "Error: Divert Stream OFF."
#define STR_TEXT_FM_ERR_DIVERT_STREAM  "Error: Divert Stream."
#define STR_TEXT_FM_ERR_WAKEUP_BBB     "Error: Wakeup Babyboard B failed."
//#define STR_TEXT_FM_ERR_HF_UNDEFINED   "Error: Undefined error in Hex file."
//#define STR_TEXT_FM_ERR_HF_LINE_TOO_LONG "Error: Hex line too long ."
//#define STR_TEXT_FM_ERR_READ_NO_RESPONSE "Error during reading: No response from node"
//#define STR_TEXT_FM_ERR_READ_INVALID_ADDRESS "Error during reading: Invalid address"
//#define STR_TEXT_FM_ERR_READ_CHECKSUM  "Error during reading: Checksum error"
//#define STR_TEXT_FM_ERR_READ_UNDEF     "Error during reading: Undefined error"
#define STR_TEXT_FM_ERR_VERIFY_ERR     "Mismatch in address"
#define STR_TEXT_FM_ERR_VERIFY_ABORT   "Too many differences -> aborting"
//#define STR_TEXT_FM_ERR_VERIFY_UNEXP   "Error: Unexpected Hex file command ."
#define STR_TEXT_FM_VERIFY_MATCH       "Hex file and server's Flash contents match ."
#define STR_TEXT_FM_VERIFY_TOTAL_DIFFERENCES "Total differences:"
#define STR_TEXT_FM_RESETTING          "!!! Resetting node !!!"
#define STR_TEXT_FM_TURN_ON            "!!! Turn node on !!!"
#define STR_TEXT_FM_RESETTING_S        "!!! Resetting node(s) !!!"
#define STR_TEXT_FM_TURN_ON_S          "!!! Turn node(s) on !!!"
#define STR_TEXT_FM_CORRECT_CID        "Correct company ID:"
#define STR_TEXT_FM_NO_NODES_FOUND     "No nodes found."
#define STR_TEXT_FM_WAKEUP_SNR_OK      "Wakeup with Serial Number successful."
//#define STR_TEXT_FM_COMPARED_LINE      "Compared line"
#define STR_TEXT_FM_DIVERT_STREAM_OFF_OK "Divert Stream OFF OK."
#define STR_TEXT_FM_DIVERT_STREAM_OK   "Divert Stream OK."
#define STR_TEXT_FM_WAKEUP_BBB         "Wakeup Babyboard B."
#define STR_TEXT_FM_WAKEUP_BBB_OK      "Wakeup Babyboard B OK."
#define STR_TEXT_FM_DIVERT_STREAM_BBB  "Divert Stream to Babyboard"
//#define STR_TEXT_FM_PREPARING_DL       "Preparing download ..."
#define STR_TEXT_FM_WRITING            "Writing ..."
#define STR_TEXT_FM_LINE               "Line"
#define STR_TEXT_FM_FINISHED           "Flashing finished."
#define STR_TEXT_FM_CONNECTED_NODE     "Connected to node "
#define STR_TEXT_FM_FLASHING_FINISHED  "Flashing finished ..."
#define STR_TEXT_FM_ERR_DISPATCHER_NA  "C_XFLFlashWrite::Execute CAN Dispatcher not set."
#define STR_TEXT_FM_ERR_VERSION_MISMATCH \
   "C_XFLFlashWrite::Execute Version of class does not match version that caller expects to be using ."
#define STR_TEXT_FM_ERR_XFL_EXCHANGE   "Could not enter XFL-Exchange mode"
#define STR_TEXT_FM_XFL_EXCHANGE       "Entered XFL-Exchange mode"
#define STR_TEXT_FM_ERR_FL_PROTOCOL_VERSION     "Flashloader protocol version: < V3.00r0"
#define STR_TEXT_FM_FL_PROTOCOL_VERSION         "Flashloader protocol version: V%x.%x%xr%x"
#define STR_TEXT_FM_ERR_READ_IMPL_INFO          "Could not read implementation information."
#define STR_TEXT_FM_ERR_READ_FINGER_PRINT       "Could not read list of available finger print information."
#define STR_TEXT_FM_ERR_FINGER_PRINT_NA         "Finger print not supported by node ..."
#define STR_TEXT_FM_ERR_USER_ABORT              "Aborted by user."
#define STR_TEXT_FM_ERR_RD_SNR_CDN_WAKE         "Get SNR failed. Could not wake up node."
#define STR_TEXT_FM_TXT_SET_PARA_PT1            "Set parameter "
#define STR_TEXT_FM_TXT_SET_PARA_PT2            "\r\nValue: "
#define STR_TEXT_FM_ERR_SET_DIVERT_STREAM_PARA  "Error: Could not set divert stream parameter."
#define STR_TEXT_FM_ERR_RD_NUM_FLASH_IC         "Unable to read number of flash ICs ."

//message boxes
#define STR_TEXT_FM_COMM_RS232_WARN        "Communication via RS232. Send ID cannot be detected."
#define STR_TEXT_FM_ERR_INVALID_SNR        "Invalid Serial Number (format: 00.112233.4455)"
//#define STR_TEXT_FM_ERR_QUEUE_FULL         "CAN Hardware Error: Could not send message (possibly wrong baudrate)."
//#define STR_TEXT_FM_ERR_TOO_MANY_NODES     "Too many nodes with same ID."
#define STR_TEXT_FM_ERR_NO_RESPONSE        "No response from node"
//#define STR_TEXT_FM_ERR_WRONG_CID          "Wrong company ID"
//#define STR_TEXT_FM_ERR_READ_SNR           "Unable to read SNR."
#define STR_TEXT_FM_ERR_MULTI_ID \
   "More than one node with the same ID was found. To address one node use the 'address by Serial Number' functions ."
#define STR_TEXT_FM_ERR_CREATE_FILE        "Could not create file"
#define STR_TEXT_FM_ERR_SEND_ID_NOT_NUMBER "Send ID must be a number (max. 0x7FE/STD or 0x1FFFFFFE/XTD))."
#define STR_TEXT_FM_ERR_HEX_FILE_NO_EXIST  "Selected hex file does not exist."
#define STR_TEXT_FM_ERR_RD_HF_EOF          "Error reading hex file: No EOF record"
#define STR_TEXT_FM_ERR_RD_HF_LINE_SYNTAX  "Error reading hex file: Wrong syntax in line"
#define STR_TEXT_FM_ERR_RD_HF_LINE_CHECKSUM "Error reading hex file: Wrong checksum in line"
#define STR_TEXT_FM_ERR_RD_HF_LINE_COMMAND "Error reading hex file: Wrong command in line"
#define STR_TEXT_FM_ERR_RD_HF_MEMORY       "Error reading hex file: Out of memory"
#define STR_TEXT_FM_ERR_RD_HF_OPEN_FILE    "Error reading hex file: File not found"
#define STR_TEXT_FM_ERR_RD_HF_UNDEFINED    "Error reading hex file: Undefined error"
#define STR_TEXT_FM_NUM_BYTES_IN_FILE      "Number of bytes:"
#define STR_TEXT_FM_FILE_FILTERED          "File has been filtered"
#define STR_TEXT_FM_SAVE_CONFIGURATION     "Save Configuration"
#define STR_TEXT_FM_ENTER_NAME             "Enter name:"

#define STR_TEXT_FM_ERR_RD_PSEC_INFO       "Unable to read protected sectors information ."
#define STR_TEXT_FM_ERR_RD_MEM_SIZE_IC     "Unable to read total memory size of flash IC "
#define STR_TEXT_FM_ERR_RD_SEC_OFFSET_IC   "Unable to read sector zero offset for IC "
#define STR_TEXT_FM_ERR_RD_MAX_ERASE       "Unable to read max. sector erase time for IC "
#define STR_TEXT_FM_ERR_RD_MAX_PRG_TIME    "Unable to read max. programming time for IC "
#define STR_TEXT_FM_ERR_RD_NUM_REGIONS     "Unable to read number of regions for IC "
#define STR_TEXT_FM_ERR_RD_REGION_INFO_IC  "Unable to read flash region information for IC "
#define STR_TEXT_FM_ERR_TRANSMISSION_ERR   "Error: Transmission error."
#define STR_TEXT_FM_ERR_DURING_FLASH_PROG  "Error: Error during flash programming."
#define STR_TEXT_FM_ERR_DURING_DEL         "Error: Error during deletion."
#define STR_TEXT_FM_ERR_BITRATE            "Error: Bit rate not possible."
#define STR_TEXT_FM_ERR_INVALID_PARA       "Error: Invalid parameter."
#define STR_TEXT_FM_ERR_EEP_VERIFY         "Error: EEPROM verify error."
#define STR_TEXT_FM_ERR_EEP_READ           "Error: EEPROM read error."
#define STR_TEXT_FM_ERR_DIVERT_STREAM_TRG_GW       "Error: Communication error between gateway and divert target."
#define STR_TEXT_FM_ERR_HEX_CMD_UNK        "Error: Unknown command in a hex file line."
#define STR_TEXT_FM_TXT_NUM_NODES          "Number of nodes found: "
#define STR_TEXT_FM_TXT_NODE_WAKE_PT1      "Node "
#define STR_TEXT_FM_TXT_NODE_WAKE_PT2      ": Wakeup failed. Could not detect serial number and device type."
#define STR_TEXT_FM_TXT_NODE_SNR_PT1       "Node "
#define STR_TEXT_FM_TXT_NODE_SNR_PT2       ": Get SNR failed. Could not detect serial number and device type. "
#define STR_TEXT_FM_TXT_SURP_NODE_AMBIG_ID "Surplus node found with ambiguous ID "
#define STR_TEXT_FM_ERR_DEV_ID_TYPE        "get-device-ID failed ! Could not detect device type."
#define STR_TEXT_FM_ERR_WAKE_SNR_PT1       "Node "
#define STR_TEXT_FM_ERR_WAKE_SNR_PT2       ": Wakeup-SNR failed ! Could not detect device type. "
#define STR_TEXT_FM_ERR_WAKE_SNR_PT3       "Please check the company ID "
#define STR_TEXT_FM_ERR_RE_LOI             ": Fingerprint: Could not read list of available information."
#define STR_TEXT_FM_ERR_RE_PROG_DATE       ": Fingerprint: Could not read programming date."
#define STR_TEXT_FM_ERR_RE_PROG_TIME       ": Fingerprint: Could not read programming time."
#define STR_TEXT_FM_ERR_RE_USER_NAME       ": Fingerprint: Could not read user name."
#define STR_TEXT_FM_ERR_RE_CHECKSUM        ": Fingerprint: Could not read checksum."
#define STR_TEXT_FM_ERR_RE_DEV_INFO_ADDR   ": Device info: Could not read device info address."
#define STR_TEXT_FM_ERR_IMPL_SERVICES      ": Unable to read which services are implemented."
#define STR_TEXT_FM_ERR_RD_HEX_REC_SUP_INF ": Unable to read hex-record support information."
#define STR_TEXT_FM_ERR_RD_CALC_CHKSM_BLK  ": Could not read calculated checksum for block "
#define STR_TEXT_FM_ERR_WR_RESET_RQ        "Could not send reset request."

//other
//#define STR_TEXT_FM_FOR_INTERNAL_USE      " for STW internal use only ["
#define STR_TEXT_FM_ERR_ONE_FILE_ONLY     "Drop only one file at a time."
#define STR_TEXT_FM_ERR_NO_HEXFILE        "Not a valid extension for a hex file."
#define STR_TEXT_FM_ERR_INI_WRITE \
   "Could not write Winflash.INI (possibly write protected). Configuration will not be saved."
//#define STR_TEXT_FB_WAKEUP_NODE          "Wakeup Node"
//#define STR_TEXT_FB_FLASH_NODE           "Flash Node"
//#define STR_TEXT_FB_SEARCH_ALL_NODES     "Search All Nodes"

// DlgXFLSearchNodeSnr
//#define STR_TEXT_DFM_SNS_CAPTION        "Results ..."
//#define STR_TEXT_DFM_SNS_LOCID_SNR      "Flash/Local ID/Serial_number"
//#define STR_TEXT_DFM_SNS_FLASH          "Flash selected nodes"
//#define STR_TEXT_DFM_SNS_CHANGE_ID      "Change Local ID"
//#define STR_TEXT_DFM_SNS_SH_NO_ECU_SELECTED "No server selected ! Select a server with click on Checklist."
//#define STR_TEXT_DFM_SNS_SELECT_ECU         "Select one of the listed servers by cursor click."

//DlgXFLSearch
#define STR_TEXT_FS_ERR_LID_NOT_NUMERIC   "Local ID must be numeric."
#define STR_TEXT_FS_ERR_LID_WRONG         "Local ID must be > 0 and < 255."
#define STR_TEXT_FS_ERR_NO_WAKEUP         "Could not wake up node."
#define STR_TEXT_FS_ERR_WRONG_CID         "Wrong company ID"
#define STR_TEXT_FS_ERR_LID_NOCHANGE      "Could not change Local ID."
#define STR_TEXT_FS_MODE_THAN_ONE_NODE \
   "Nodes with identical IDs exist in the network !\nTo address one node use the 'address by Serial Number' functions."
#define STR_TEXT_FS_INPUT_NEW_LID         "Input new Local ID (0..254)"
#define STR_TEXT_FS_LOCAL_ID              "Local ID:"
#define STR_TEXT_FS_LOCAL_ID_CHANGED      "Local ID changed"

//DlgXFLWakeup
#define STR_TEXT_FW_ERR_READ_SEC_COUNT    "Unable to read number of flash sectors."
#define STR_TEXT_FW_ERR_READ_DEV_ID       "Unable to read device ID."
#define STR_TEXT_FW_ERR_READ_ERASE_TO     "Unable to read erase timeout factor."
#define STR_TEXT_FW_ERR_READ_WRITE_TO     "Unable to read write timeout factor."
#define STR_TEXT_FW_ERR_READ_DL_COUNT     "Unable to read download count."
#define STR_TEXT_FW_ERR_READ_XFL_VER      "Unable to read flashloader version."
#define STR_TEXT_FW_ERR_READ_LID          "Unable to read Local ID."
#define STR_TEXT_FW_ERR_READ_SNR          "Unable to read serial number."
#define STR_TEXT_FW_ERR_READ_BBB_SEC_COUNT "Unable to read BBB SectorCount."
#define STR_TEXT_FW_ERR_READ_BBB_XFL_VER  "Unable to read BBB flashloader version number."
#define STR_TEXT_FW_ERR_READ_BBB_LAST_USER "Unable to read BBB last user signature."
#define STR_TEXT_FW_ERR_DEV_ID_NOT_SUPP   "Device ID: function not supported"
#define STR_TEXT_FW_ERR_DIVERT_NOT_SUPP   "ESX flashloader does not support BBB divert stream."
#define STR_TEXT_FW_ERR_WAKEUP_BBB        "Wakeup Babyboard B failed."
#define STR_TEXT_FW_ERR_DIVERT_FAILED     "Divert stream failed."
#define STR_TEXT_FW_ERR_DIVERT_OFF_FAILED "Divert stream off failed."
#define STR_TEXT_FW_ERR_LID_NOCHANGE      "Could not change Local ID."
#define STR_TEXT_FW_ERR_SEND_TO_SLEEP     "Unable to send node to sleep."
#define STR_TEXT_FW_ERR_NO_RESPONSE       "No response."
#define STR_TEXT_FW_ERR_NO_SEC_SELECTED   "Select a block from the list first"
#define STR_TEXT_FW_ERR_SEC_COUNT_IVALID  "Sector count invalid."
#define STR_TEXT_FW_ERR_READ_CRC          "Could not read CRC."
#define STR_TEXT_FW_NUM_SECTORS           "Number of flash sectors:"
#define STR_TEXT_FW_DEV_ID                "Device ID:"
#define STR_TEXT_FW_FLASHLOADER_VER       "Flashloader version:"
#define STR_TEXT_FW_DOWNLOAD_COUNT        "Download count:"
#define STR_TEXT_FW_SNR                   "Serial number:"
#define STR_TEXT_FW_BBB_LAST_STW          "Last flashed by: STW"
#define STR_TEXT_FW_BBB_LAST_CUST         "Last flashed by: customer"
#define STR_TEXT_FW_BBB_LAST_UNDEF        "Last flashed by: undefined"
#define STR_TEXT_FW_BBB_LAST_XXX          "Last flashed by: ???"
#define STR_TEXT_FW_LOCAL_ID_CHANGED      "Local ID changed"
#define STR_TEXT_FW_BITRATE_CHANGED       "Bitrate changed."
#define STR_TEXT_FW_SEND_ID_CHANGED       "Send ID changed."
#define STR_TEXT_FW_CRC_WRITTEN \
   "The CRC was written to the server. \nDo NOT turn off the server without \nselecting SLEEP,RETURN or RESET first."
#define STR_TEXT_FW_ERASE_TO_CHANGED      "Erase timeout factor changed."
#define STR_TEXT_FW_WRITE_TO_CHANGED      "Write timeout factor changed."
#define STR_TEXT_FW_WARN_CLOSE \
   "In order to update the checksum in the server this dialog\nshould not be closed without selecting SLEEP, RETURN or RESET. \nAre you sure to quit without correcting the checksum ?"
//#define STR_TEXT_FW_CONFIRM_SET_COMP_MODE "Set compare mode of sector"
#define STR_TEXT_FW_COMP_MODE_CHANGED \
   "Compare mode was changed on the server. \nDo NOT turn off the server without \nselecting SLEEP,RETURN or RESET first."

//XFL error responses
#define STR_TEXT_XFL_ERR_NO_RESPONSE      "No response from node."
//#define STR_TEXT_XFL_ERR_SET_BTR          "Bitrate could not be set."
//#define STR_TEXT_XFL_ERR_SET_ID           "Send ID could not be set."
//#define STR_TEXT_XFL_ERR_INVALID_BITRATE  "Invalid bitrate."
//#define STR_TEXT_XFL_ERR_INVALID_SECTOR   "Sector out of range."
#define STR_TEXT_XFL_ERR_INVALID_PARAMETER "Invalid parameter."
#define STR_TEXT_XFL_ERR_EEPROM_WRITE     "Error: EEPROM write error."
#define STR_TEXT_XFL_ERR_UNDEFINED_CODE   "Undefined error code."
#define STR_TEXT_XFL_ERR_UNDEFINED_ERR    "Undefined error."
//#define STR_TEXT_XFL_ERR_WAKE_UP_SNR_LONG   "Error: wake up SNR not supported (LONG_SNR_MODE)."
//#define STR_TEXT_XFL_ERR_NUM_SELECTED_ECU   "Error: number of selected nodes must be 1."
//#define STR_TEXT_XFL_ERR_NO_INIT_PROGRAM_FLASH "Error: program flash components are not initialized."
//#define STR_TEXT_XFL_ERR_SET_ONE_ECU_ACTIVE "Error: set one node ACTIVE and verify."
//#define STR_TEXT_XFL_ERR_NODE_SLEEP         "Error: could not set node into sleep."
//#define STR_TEXT_XFL_ERR_READ_LID           "Error: can not read Local ID."
//#define STR_TEXT_XFL_ERR_READ_SNR           "Error: can not read Serial Number."
#define STR_TEXT_XFL_ERR_SNR_TO_CANDATA     "Error: can not convert Serial Number to can data."
//#define STR_TEXT_XFL_ERR_NUM_ECU_BIG_0      "Error: number of found ECUs must be bigger than 0."

//VisuComponents
#define STR_TEXT_VIS_ERR_IWR           "Could not write value to server."
#define STR_TEXT_VIS_ERR_LOAD_BITMAP   "Load bitmap from stream error.\nIs it a valid BMP file ?"
#define STR_TEXT_VIS_ERR_LOAD_WAV      "Load WAV file from stream error."
#define STR_TEXT_VIS_ERR_LOAD          "Error loading from file"
#define STR_TEXT_VIS_EXT_NOT_BMP       "Files must have the extension '.BMP'."
#define STR_TEXT_VIS_EXT_NOT_WAV       "Files must have the extension '.WAV'."
#define STR_TEXT_VIS_ANGLE             "Pointer Instrument: Reserve angle must be >= 0 and <= 360"
#define STR_TEXT_VIS_SCALES            "Pointer Instrument: Number of scales must be >= 0 and <= 20"

//Data Sources
#define STR_TEXT_DS_ERR_NO_VALID_NAME_IN_LIST "List does not contain a valid name."
//#define STR_TEXT_DS_ERR_NO_LISTS_FOUND        "No E2Edit lists for this device have been found."
#define STR_TEXT_DS_ERR_NO_RAM_LISTS_FOUND    "No variable list files have been found."
//#define STR_TEXT_DS_ERR_DEF_FILE_NO_EXIST     "DEF file does not exist."
#define STR_TEXT_DS_ERR_OPEN_COMMENTS_FILE    "Could not open comments file."
#define STR_TEXT_DS_ERR_READ_DATA_VERSION     "Could not read data version."
#define STR_TEXT_DS_ERR_WRITE_COMMENTS_FILE   "Could not save comments file."
#define STR_TEXT_DS_ERR_UNKNOWN_LIST          "Unknown list."
#define STR_TEXT_DS_ERR_DOES_NOT_EXIST        "does not exist."
#define STR_TEXT_DS_ERR_DOES_NOT_MATCH_DEF    "does not match DEF file."
#define STR_TEXT_DS_ERR_WILL_BE_DELETED       "will be deleted."
#define STR_TEXT_DS_ERR_CANNOT_DELETE         "Cannot delete"
#define STR_TEXT_DS_ERR_NO_READ_DUE_TO_LEVEL  "Variable may not be read with the actual user level"
#define STR_TEXT_DS_ERR_NO_WRITE_DUE_TO_LEVEL "Variable may not be written with the actual user level"
#define STR_TEXT_DS_ERR_SENDING_REQUEST       "Error sending request."
#define STR_TEXT_DS_ERR_NO_RESPONSE           "No response from node."
#define STR_TEXT_DS_ERR_ERR_RESPONSE          "Error response."
#define STR_TEXT_DS_ERR_PROJECT_NO_MATCH      "Project does not match, login is not possible."
#define STR_TEXT_DS_ERR_NUMERIC_TOO_LONG      "Numeric values must be <= 4 bytes."
#define STR_TEXT_DS_ERR_NOT_NUMERIC           "Value must be numeric."
#define STR_TEXT_DS_ERR_VALUE_OO_RANGE        "Value out of range."
#define STR_TEXT_DS_ERR_STRING_LENGTH         "String too long."
#define STR_TEXT_DS_ERR_FALSE_RESPONSE        "False response from server"
#define STR_TEXT_DS_ERR_VERIFY                "Verify error."
#define STR_TEXT_DS_ERR_USE_WRITE_LIST_CHANGED "More than one value changed! Use function 'Write List Changed' "
#define STR_TEXT_DS_ERR_WRITING_CHECKSUM      "Error writing checksum."
#define STR_TEXT_DS_ERR_INVALID_VALUE \
   "All list values need to be known to calculate the list CRC.\nUnknown value for parameter '"
#define STR_TEXT_DS_ERR_READ_NEW_VALUES       "Read whole parameter list values from server first."
#define STR_TEXT_DS_ERR_ERASE_FILE            "Could not erase file."
#define STR_TEXT_DS_ERR_FILE_NOT_FOUND        "File does not exist."
//#define STR_TEXT_DS_ERR_VIEW_NO_MATCH         "View in DAT-file does not match the actual view, continue reading ?"
#define STR_TEXT_DS_ERR_NOT_FOUND_CONTINUE    "DAT-file contains variables that are not part of the project (ignored)."
#define STR_TEXT_DS_ERR_IS_EMPTY              "' is empty ! Continue ?"
#define STR_TEXT_DS_ERR_OVERWRITE_OPENED      "Could not overwrite existing file, is it opened ?"
#define STR_TEXT_DS_ERR_INVALID_PARAM_SIZE    "Invalid parameter size."
#define STR_TEXT_DS_ERR_INVALID_PARAM_TYPE    "Invalid parameter type."
#define STR_TEXT_DS_ERR_OVERWRITE_EXISITING   "does already exist. Overwrite file ?"
#define STR_TEXT_DS_ERR_CREATE_C_FILE         "Could not create file."
//#define STR_TEXT_DS_ERR_CREATE_H_FILE         "Could not create .H file."
#define STR_TEXT_DS_ERR_WRITE_TO_FILE         "Error writing to file."
#define STR_TEXT_DS_ERR_DATA_VER_NOT_NUMERIC  "DATA VERSION must be numeric."
#define STR_TEXT_DS_ERR_NO_BACKUP_POSSIBLE    "Could not create backup file."
//#define STR_TEXT_DS_ERR_UNKNOWN_LIST_NAME     "Unknown listname in tEEPROMListDefinition-List"
//#define STR_TEXT_DS_ERR_UNKNOWN_LIST_NAME_RAM "Unknown listname in tRAMListDefinition-List"
//#define STR_TEXT_DS_ERR_UNKNOWN_CRC_INFO      "Unknown CRC info in tEEPROMListDefinition-List"
#define STR_TEXT_DS_ERR_NO_LISTS_FOUND_FILE   "No variable lists found, is it the correct file ?"
#define STR_TEXT_DS_ERR_COMM_FILE_NO_EXISTS   "Comments file does not exist."
#define STR_TEXT_DS_ERR_COMM_FILE_NO_MATCH    "Comments file does not match DEF file."
#define STR_TEXT_DS_ERR_COMM_TOO_MANY_LANG    "Comments file must not contain > 5 languages."
#define STR_TEXT_DS_ERR_COMM_INVALID_LANGUAGE "Invalid language name in comments file."
#define STR_TEXT_DS_ERR_REFERENCES_REMOVE \
   "References to invalid lists and variables have been removed from comments."
#define STR_TEXT_DS_ERR_IMP_INVALID_TYPE      "Invalid type in INI file."
#define STR_TEXT_DS_ERR_IMP_INVALID_STR_LEN   "Invalid size of string."
#define STR_TEXT_DS_ERR_AARGHH                "Aaaaarrrghhhh"
#define STR_TEXT_DS_ERR_SEND_ABORT_RQ         "Error sending abort request"
#define STR_TEXT_DS_ERR_ADD_CYCLIC_LIST       "Could not add to cyclic transmission list."

#define STR_TEXT_DS_SCANNING_FOR_RAM  "Scanning for RAM files ..."
#define STR_TEXT_DS_ERR_PROJECT_NO_MATCH_DAT "The project was changed since the data set was saved ! Continue reading ?"

#define STR_TEXT_DS_READING_COM_FILE  "Loading comments file ..."
#define STR_TEXT_DS_READING_DATA_VER  "Loading defaults ..."

#define STR_TEXT_DS_WRITING_RAM_FILE  "Writing RAM file ..."
#define STR_TEXT_DS_WRITING_COM_FILE  "Writing comments file ..."
#define STR_TEXT_DS_WRITING_DATA_VER  "Writing data version ..."
#define STR_TEXT_DS_FINISHED          "Finished ..."
#define STR_TEXT_DS_ERROR_DDD         "Error ..."
#define STR_TEXT_DS_READING_LIST      "Reading"
#define STR_TEXT_DS_WRITING_LIST      "Writing"
#define STR_TEXT_DS_COMPARE_LIST      "Comparing"
#define STR_TEXT_DS_ADDRESS           "address"
#define STR_TEXT_DS_UNKNOWN_SIZE      "Unknown size:"
#define STR_TEXT_DS_UNKNOWN_TYPE      "Unknown type:"
#define STR_TEXT_DS_UPDATE_OF_TASK    "Update of Task '"
#define STR_TEXT_DS_CONFIRMED         "' confirmed by server."
#define STR_TEXT_DS_INVALID_TYPE      ": invalid type."
#define STR_TEXT_DS_INVALID_ACC_TYPE  ": invalid access type."
#define STR_TEXT_DS_INDEX             "index"

//KFXFlashloader
#define STR_TEXT_XFL_ERR_INVALID_RESET_FORMAT "WinFlash: Reset message has invalid format."

//KFXProcess
#define STR_TEXT_KFX_NO_DONGLE_PASSWORD   "No dongle found -> Password mode"
#define STR_TEXT_KFX_BGROUP_RANGE         "bGroup must be <= 10"
//#define STR_TEXT_KFX_NEW_DEVICE_NAME      "Enter a device name for this project"
#define STR_TEXT_KFX_DEF_FILTER           "Device definition files (*.DEF)|*.DEF"
#define STR_TEXT_KFX_SELECT_FILE_NAME     "Select a file name for this configuration"
#define STR_TEXT_KFX_EXISTS_OVERWRITE     "File already exists, overwrite it ? (No will append to the existing file)"
#define STR_TEXT_KFX_OVERWRITE_ALL \
   "Overwrite corresponding files as well ?\n Selecting NO will append to the existing files."
#define STR_TEXT_KFX_ERR_INVALID_DEF_FILE "Could not append to exisiting DEF file: wrong checksum."
//#define STR_TEXT_KFX_NO_DYNAMIC_LANGUAGE  "Dynamic language switching is only possible using dynamic loading of
// packages (use VisLibRT.bpl)."

//XFLDownload
#define STR_TEXT_FDL_VERSION_ERR  "Flashloader version could not be read: "
//#define STR_TEXT_FDL_VERSION_ERR_NO_SUPP  "Error: Flashloader version not supported."
//#define STR_TEXT_FDL_VERSION_ERR_UNDEF_CODE "Error: Flashloader version could not be read: Undefined error code."
//#define STR_TEXT_FDL_VERSION_ERR_UNDEF    "Error: Flashloader version could not be read: Undefined error."
#define STR_TEXT_FDL_DIVERT_ERR_NO_SUPP   "Error: Flashloader does not support divert stream."
#define STR_TEXT_FDL_VERSION_BBB_ERR_NO_RESP  "Error: BBB Flashloader version could not be read: No Response."
#define STR_TEXT_FDL_VERSION_BBB_ERR_NO_SUPP  "Error: BBB Flashloader version not supported."
#define STR_TEXT_FDL_VERSION_BBB_ERR_UNDEF_CODE \
   "Error: BBB Flashloader version could not be read: Undefined error code."
#define STR_TEXT_FDL_VERSION_BBB_ERR_UNDEF    "Error: BBB Flashloader version could not be read: Undefined error."
#define STR_TEXT_FDL_ERR_C_APPL_NOT_POSSIBLE  "Error: C application for Babyboard not possible with sector count < 3."
#define STR_TEXT_FDL_ERR_CANOPEN_NOT_POSSIBLE "Error: CANopen config download not possible with sector count < 3."
#define STR_TEXT_FDL_ERR_IECAPPL_NOT_POSSIBLE \
   "Error: IEC application download not possible with sector count of server."
#define STR_TEXT_FDL_ERR_IECRTS_NOT_POSSIBLE  "Error: IEC run-time-system not possible with sector count of server."
#define STR_TEXT_FDL_ERR_SEC_ERASE_INVALID    "Error: Sectors to erase invalid."
#define STR_TEXT_FDL_ERR_WRITING_CRCS     "Error: Could not write CRC."
#define STR_TEXT_FDL_ERR_FLASHING         "Error while flashing."
#define STR_TEXT_FDL_ERR_SEC_ERASE_INV2   "Error: sector number to erase must be < sector count."
#define STR_TEXT_FDL_ERR_ERASE            "Error erasing sector"
//#define STR_TEXT_FDL_ERR_ERASE_NO_RESP    "No response from node"
//#define STR_TEXT_FDL_ERR_ERASE_NO_ACT     "Could not be erased"
//#define STR_TEXT_FDL_ERR_ERASE_NO_INVALID "Invalid sector number"
#define STR_TEXT_FDL_ERR_ERASE_NO_CODE    "Error: Node specific error code 0x"
//#define STR_TEXT_FDL_ERR_ERASE_NO_UNDEF_CODE "Undefined error code"
//#define STR_TEXT_FDL_ERR_ERASE_NO_UNDEF   "Undefined error"
//#define STR_TEXT_FDL_ERR_WRITE_NO_RESP    "Error writing: No response or TX error (line"
//#define STR_TEXT_FDL_ERR_WRITE_NO_ACT     "Error writing: Programming error (line"
#define STR_TEXT_FDL_ERR_WRITE_CHECKSUM   "Error writing: Checksum error (line"
//#define STR_TEXT_FDL_ERR_WRITE_INV_COMM   "Error writing: Invalid command (line"
//#define STR_TEXT_FDL_ERR_WRITE_INV_ADDR   "Error writing: Invalid address (line"
//#define STR_TEXT_FDL_ERR_WRITE_CODE       "Error writing: Error code (line"
//#define STR_TEXT_FDL_ERR_WRITE_UNDEF_CODE "Error writing: Undefined error code (line"
//#define STR_TEXT_FDL_ERR_WRITE_VERIFY     "Error writing: Server reports checksum different from checksum in hex file
// (line"

#define STR_TEXT_FDL_SEC_COUNT_ERR        "Error: Number of sectors could not be read."
#define STR_TEXT_FDL_NUM_SECTORS          "Number of Flash sectors:"
#define STR_TEXT_FDL_WRITING_CRCS         "Writing checksums ..."
#define STR_TEXT_FDL_CRCS_NO_SUPP         "Server does not support flash checksums"
#define STR_TEXT_FDL_TOTAL_TIME           "Total time:"
#define STR_TEXT_FDL_FILE_NOT_FOUND       "Error: hex file not found"
#define STR_TEXT_FDL_SEC_ERASE            "Sectors to erase:"
#define STR_TEXT_FDL_ERASING              "Erasing ..."
#define STR_TEXT_FDL_ERASING_SECTOR       "Erasing sector"
#define STR_TEXT_FDL_ERASE_TIME           "Total erase time:"
#define STR_TEXT_FDL_BYTES                "Bytes"
#define STR_TEXT_FDL_BYTE                 "Byte"
#define STR_TEXT_FDL_DOWNLOAD_TIME        "Total download time:"
#define STR_TEXT_FDL_AVERAGE_RATE         "Average rate:"
#define STR_TEXT_FDL_UNKNOWN_ERR          "Unknown error"

#define STR_TEXT_FDL_DFM_RGSELEC_NODE_RESET "Start program (node reset)"
#define STR_TEXT_FDL_DFM_RGSELEC_NET_RESET  "Start all nodes (net reset)"
#define STR_TEXT_FDL_DFM_RGSELEC_STAY_SLEEP "Do not start (stay in sleep mode)"
#define STR_TEXT_FDL_DFM_RGSELEC_NODE_RETURN "Start program (node return)"
#define STR_TEXT_FDL_DFM_RGSELEC_NET_START   "Start all nodes (net start)"

#define STR_TEXT_FDL_SBC_SUPPORTED        "Sector based checksums supported by this node"
#define STR_TEXT_FDL_BBC_SUPPORTED        "Block based checksums supported by this node"
#define STR_TEXT_FDL_CS_DEACTIVATED       "Checksum functionality deactivated"
#define STR_TEXT_FDL_ERR_FL_IMPLEMENTATION \
   "Error: flashloader implementation problem (number of sectors does not match flash information table)."
#define STR_TEXT_FDL_ERR_HEX_ON_PROTECTED_S        "Error: Hex file data occupies protected flash sector."
#define STR_TEXT_FDL_HINT_USE_AUTO_MODE \
   "Hint: With this server node flashing with the 'Automatic' setting can improve flashing performance."
#define STR_TEXT_FDL_ERR_ONLY_F_AUTO_UD \
   "Error: Only file types 'Automatic' and 'user defined' can be used from flashloader protocol version V3.00r0 on."
#define STR_TEXT_FDL_ERR_FILETYPE_AUTO_NA \
   "Error: File type 'Automatic' can not be used with flashloader protocol versions below V3.00r0."
#define STR_TEXT_FDL_ERR_INVALID_HEX_FILE          "Error: Invalid type of hexfile selected."
#define STR_TEXT_FDL_ERR_WR_PROG_DATA              "Error: could not write programming date"
#define STR_TEXT_FDL_ERR_WR_PROG_TIME              "Error: could not write programming time"
#define STR_TEXT_FDL_ERR_RD_USER_NAME              "Could not read user name from Windows system."
#define STR_TEXT_FDL_ERR_WR_USER_NAME              "Error: could not write user name"
#define STR_TEXT_FDL_ERR_WR_APPL_CHECKS            "Error: could not write application checksum"
#define STR_TEXT_FDL_TXT_REC_USER_N_P1             "Recording username '"
#define STR_TEXT_FDL_TXT_REC_USER_N_P2             "' on node."
#define STR_TEXT_FDL_TXT_IGNORE                    " -> ignoring"
#define STR_TEXT_FDL_ERR_RD_HEX_REC_INFO           "Unable to read hex-record support information."
#define STR_TEXT_FDL_TXT_CHG_HEX_REC_LENGTH        "Changing hex record length to the maximum supported by the node ("
#define STR_TEXT_FDL_TXT_DO_CHG_HEX_REC_LENGTH     "Changing hex record length to "
#define STR_TEXT_FDL_ERR_ENTER_PROG_MODE           "Could not enter programming mode."
#define STR_TEXT_FDL_TXT_WR_FLASH_DO               "Writing to Flash ..."
#define STR_TEXT_FDL_ERR_WR_FLASH_DO_PT1           "Error writing: "
#define STR_TEXT_FDL_ERR_WR_FLASH_DO_PT2           " Line:"
#define STR_TEXT_FDL_ERR_USER_ABORT                "Aborted by user."
#define STR_TEXT_FDL_WARN_COULD_NOT_CALC_APPL_CHK  "Warning: could not calculate application checksum"
#define STR_TEXT_FDL_WARN_COULD_NOT_WR_APPL_CHK    "Warning: could not write application checksum"
#define STR_TEXT_FDL_ERR_CFG_DIC                   "Error: invalid configuration of device_id_check."
#define STR_TEXT_FDL_TXT_ID_CHECK_PASSED           "ID check: not active -> passed."
#define STR_TEXT_FDL_TXT_ID_OF_HEX_FILE            "ID check: scanning hex file for ID ..."
#define STR_TEXT_FDL_TXT_ID_CHECKING               "ID check: checking for ID ..."
#define STR_TEXT_FDL_TXT_ID_CHECK_NODE_HEX \
   "ID check: Could not read device ID address from node, scanning hex file for ID ..."
#define STR_TEXT_FDL_TXT_ID_CHECK_ADDR_NA \
   "ID check: Address not available on node, scanning hex file for ID ..."
#define STR_TEXT_FDL_ERR_ID_CHECK_RD_NODE          "ID check: Error reading device ID address from node ..."
#define STR_TEXT_FDL_ERR_ID_CHECK_ID_ADDR_NA       "ID check: Error: Device ID address not available on node."
#define STR_TEXT_FDL_ERR_ID_CHECK_ID_NA_HEX        "ID check: Device ID not found in hex file."
#define STR_TEXT_FDL_ERR_ID_CHECK_ID_AMBIG_HEX     "ID check: Ambiguous Device IDs found in hex file."
#define STR_TEXT_FDL_ERR_ID_CHECK_ID_UNDEF         "ID check: Error: undefined."
#define STR_TEXT_FDL_ERR_ID_CHECK_IGNOR            "ID check: Ignoring problems ..."
#define STR_TEXT_FDL_TXT_ID_NA_CHECK_HEX_FILE      "ID check: Could not get device ID from hex file."
#define STR_TEXT_FDL_ID_CHECK_MATCH                "ID check: match ..."
#define STR_TEXT_FDL_ERR_ID_CHECK_MISMATCH_PT1     "ID check: Mismatch: Hex File: '"
#define STR_TEXT_FDL_ERR_ID_CHECK_MISMATCH_PT2     "' Target: '"
#define STR_TEXT_FDL_TXT_WR_FLASH_RQ               "Sending FLASH request ..."

//XFLUpload
//#define STR_TEXT_FUL_ERR_START_ADDR_INVALID "Start Address must be multiple of 32."
#define STR_TEXT_FUL_ERR_ADDR_OVERLAP   "End Address must be greater than Start Address."
//#define STR_TEXT_FUL_ERR_NO_RESP        "Error during reading: No response from node"
#define STR_TEXT_FUL_ERR_CHECKSUM       "Error during reading: Checksum error"
//#define STR_TEXT_FUL_ERR_INVALID_ADDR   "Error during reading: Invalid address"
//#define STR_TEXT_FUL_ERR_UNDEFINED      "Error during reading: Undefined error"
#define STR_TEXT_FUL_START_ADDR_CAPTION "Start Address"
#define STR_TEXT_FUL_START_ADDR_PROMPT  "Enter Start Address (Multiple of 32d)"
#define STR_TEXT_FUL_END_ADDR_CAPTION "End Address"
#define STR_TEXT_FUL_END_ADDR_PROMPT  "Enter End Address"
#define STR_TEXT_FUL_SPARE_IRAM       "Spare ESX IRAM AREA"
#define STR_TEXT_FUL_READING_FINISHED "Reading finished."
#define STR_TEXT_FUL_READING_FINISHED_BOX "Data written to file."
#define STR_TEXT_FUL_ERROR            "Error: Stopped."
//#define STR_TEXT_FUL_ADDRESS_RANGE    "Address range:"
#define STR_TEXT_FUL_WRITING_TO_FILE  "Writing to file ..."
#define STR_TEXT_FUL_CURRENT_ADDRESS  "Current address:"

//FORM TEXTS
//General Texts
#define STR_TEXT_DFM_OK     "OK"
#define STR_TEXT_DFM_CANCEL "Cancel"
#define STR_TEXT_DFM_MENU_FILE   "&File"
#define STR_TEXT_DFM_MENU_EXIT   "&Exit"
#define STR_TEXT_DFM_MENU_HELP   "&Help"
#define STR_TEXT_DFM_MENU_ABOUT  "&About"
#define STR_TEXT_DFM_YES         "Yes"
#define STR_TEXT_DFM_YES_ALL     "Yes for all"

//DlgCANInterface
#define STR_TEXT_DFM_CI_CAPTION  "CAN Interface"
#define STR_TEXT_DFM_CI_DLL      "Hardware DLL:"
#define STR_TEXT_DFM_CI_BITRATE  "Bitrate:"

//DlgCMONFilter
#define STR_TEXT_DFM_CF_CAPTION   "Software Receive Filters"
#define STR_TEXT_DFM_CF_CONFIG    "Filter Configuration"
#define STR_TEXT_DFM_CF_FILTER1   "Filter1:"
#define STR_TEXT_DFM_CF_FILTER2   "Filter2:"
#define STR_TEXT_DFM_CF_FILTER3   "Filter3:"
#define STR_TEXT_DFM_CF_FILTER4   "Filter4:"
#define STR_TEXT_DFM_CF_MIN       "Min"
#define STR_TEXT_DFM_CF_MAX       "Max"
#define STR_TEXT_DFM_CF_APPLY     "Apply"
#define STR_TEXT_DFM_CF_TYPE      "Filter Type"
#define STR_TEXT_DFM_CF_BLOCK     "Block specified IDs"
#define STR_TEXT_DFM_CF_PASS      "Let only specified IDs pass"

//DlgCMONMain
#define STR_TEXT_DFM_CM_HINT_SEND_CONFIG  "send configuration"
#define STR_TEXT_DFM_CM_HINT_START "start monitor"
#define STR_TEXT_DFM_CM_HINT_STOP  "stop monitor"
#define STR_TEXT_DFM_CM_HINT_TIME  "absolute/relative time"
#define STR_TEXT_DFM_CM_HINT_BASE  "decimal/hexadecimal display"
#define STR_TEXT_DFM_CM_HINT_MODE  "static/continuous display"
#define STR_TEXT_DFM_CM_HINT_PROT  "protocol on/off"
#define STR_TEXT_DFM_CM_HINT_L7    "Change L7 protocol"
#define STR_TEXT_DFM_CM_ACTIVE        "Active:"
#define STR_TEXT_DFM_CM_TX_ERRORS     "TX-Errors:"
#define STR_TEXT_DFM_CM_FPS_HINT      "Frames per second"
#define STR_TEXT_DFM_CM_FPS           "FPS:"
#define STR_TEXT_DFM_CM_ASCII_FILTER  "ASCII Files (*.txt)|*.txt"
#define STR_TEXT_DFM_CM_MENU_START_PROT "&Start Protocol"
#define STR_TEXT_DFM_CM_MENU_STOP_PROT  "&Stop Protocol"
#define STR_TEXT_DFM_CM_MENU_ACTIONS    "&Actions"
#define STR_TEXT_DFM_CM_MENU_START      "&Start"
#define STR_TEXT_DFM_CM_MENU_STOP       "&Stop"
#define STR_TEXT_DFM_CM_MENU_CONFIG     "&Config"
#define STR_TEXT_DFM_CM_MENU_BUS_PARAMS "&Bus Parameters"
#define STR_TEXT_DFM_CM_MENU_CAN_DLL    "&CAN Hardware (DLL)"
#define STR_TEXT_DFM_CM_MENU_DLL_INFO   "DLL Info"
#define STR_TEXT_DFM_CM_MENU_SEND_CONFIG "&Send Configuration"
#define STR_TEXT_DFM_CM_MENU_RX_FILTERS  "Receive &Filters"
#define STR_TEXT_DFM_CM_MENU_CAN_STATUS  "CAN Status"
#define STR_TEXT_DFM_CM_MENU_PROP_PARAMS "&Protocol Parameters"

//DlgCMONSend
#define STR_TEXT_DFM_CS_CAPTION  "Configure Send Messages"
#define STR_TEXT_DFM_CS_ADD      "&Add Msg"
#define STR_TEXT_DFM_CS_DELETE   "&Delete Msg"
#define STR_TEXT_DFM_CS_LOAD     "&Load"
#define STR_TEXT_DFM_CS_SAVE     "&Save"
#define STR_TEXT_DFM_CS_CLONE    "&Clone Msg"
#define STR_TEXT_DFM_CS_EXIT     "Exit"
#define STR_TEXT_DFM_CS_APPLY    "Apply"
#define STR_TEXT_DFM_CS_TRIGGER  "Trigger key"
#define STR_TEXT_DFM_CS_KEY      "Key:"
#define STR_TEXT_DFM_CS_INTERVAL_HINT "Cyclic s interval in ms"
#define STR_TEXT_DFM_CS_INTERVAL_CAP  "Interval:"
#define STR_TEXT_DFM_CS_ACT_HINT "Activate message"
#define STR_TEXT_DFM_CS_ACT_CAP  "Act:"
#define STR_TEXT_DFM_CS_RTR_HINT "Remote frame"
#define STR_TEXT_DFM_CS_RTR_CAP  "RTR:"
#define STR_TEXT_DFM_CS_XTD_HINT "29 Bit ID"
#define STR_TEXT_DFM_CS_XTD_CAP  "EXT:"
#define STR_TEXT_DFM_CS_DB7_HINT "Data byte 7"
#define STR_TEXT_DFM_CS_DB7_CAP  "DB7:"
#define STR_TEXT_DFM_CS_DB6_HINT "Data byte 6"
#define STR_TEXT_DFM_CS_DB6_CAP  "DB6:"
#define STR_TEXT_DFM_CS_DB5_HINT "Data byte 5"
#define STR_TEXT_DFM_CS_DB5_CAP  "DB5:"
#define STR_TEXT_DFM_CS_DB4_HINT "Data byte 4"
#define STR_TEXT_DFM_CS_DB4_CAP  "DB4:"
#define STR_TEXT_DFM_CS_DB3_HINT "Data byte 3"
#define STR_TEXT_DFM_CS_DB3_CAP  "DB3:"
#define STR_TEXT_DFM_CS_DB2_HINT "Data byte 2"
#define STR_TEXT_DFM_CS_DB2_CAP  "DB2:"
#define STR_TEXT_DFM_CS_DB1_HINT "Data byte 1"
#define STR_TEXT_DFM_CS_DB1_CAP  "DB1:"
#define STR_TEXT_DFM_CS_DB0_HINT "Data byte 0"
#define STR_TEXT_DFM_CS_DB0_CAP  "DB0:"
#define STR_TEXT_DFM_CS_DLC_HINT "Data length code (number of used bytes)"
#define STR_TEXT_DFM_CS_DLC_CAP  "DLC:"
#define STR_TEXT_DFM_CS_ID_HINT  "Message identifier"
#define STR_TEXT_DFM_CS_ID_CAP   "ID:"
#define STR_TEXT_DFM_CS_OFFSET_HINT "Send offset (after pressing trigger key) in ms"
#define STR_TEXT_DFM_CS_OFFSET_CAP  "Offset:"
#define STR_TEXT_DFM_CS_CSL_FILTER  "CMON config files (*.csl)|*.csl"

//DlgCMONStatus
#define STR_TEXT_DFM_CST_CAPTION "CAN Status"
#define STR_TEXT_DFM_CST_GB_CAP  "Status"
#define STR_TEXT_DFM_CST_BOFF    "Bus Off"
#define STR_TEXT_DFM_CST_BWARN   "Bus Warn"
#define STR_TEXT_DFM_CST_TXOVER  "TX Overflow"
#define STR_TEXT_DFM_CST_RXOVER  "RX Overflow"
#define STR_TEXT_DFM_CST_CLOSE   "Close"
#define STR_TEXT_DFM_CST_CYCLIC  "Cyclic update"

//DlgKFXCANMessageEditor/DlgXFLResetRQ
#define STR_TEXT_DFM_CME_CAPTION "Configure CAN Message"
#define STR_TEXT_DFM_CRM_CAPTION "Configure Reset Message"
#define STR_TEXT_DFM_CME_ID      "ID"
#define STR_TEXT_DFM_CME_DLC     "DLC"
#define STR_TEXT_DFM_CME_DB0     "DB0"
#define STR_TEXT_DFM_CME_DB1     "DB1"
#define STR_TEXT_DFM_CME_DB2     "DB2"
#define STR_TEXT_DFM_CME_DB3     "DB3"
#define STR_TEXT_DFM_CME_DB4     "DB4"
#define STR_TEXT_DFM_CME_DB5     "DB5"
#define STR_TEXT_DFM_CME_DB6     "DB6"
#define STR_TEXT_DFM_CME_DB7     "DB7"

//DlgKFXComSetup
#define STR_TEXT_DFM_CSE_CAPTION  "Communication Setup"
#define STR_TEXT_DFM_CSE_PROT     "Protocol Parameters"
//#define STR_TEXT_DFM_CSE_BASE_ID  "Base ID:"
//#define STR_TEXT_DFM_CSE_CLIENT   "Client (PC) Address:"
//#define STR_TEXT_DFM_CSE_SERVER   "Server (ECU) Address:"
#define STR_TEXT_DFM_CSE_INTERFACE  "Interface"
#define STR_TEXT_DFM_CSE_HARDWARE   "Hardware:"
#define STR_TEXT_DFM_CSE_CONFIG     "Config ..."

//DlgXFLMain
//DFM Texts
#define STR_TEXT_DFM_XM_WAKEUPLOCALID_ESX "Configure Node"
#define STR_TEXT_DFM_XM_READ_FROM_ESX_ESX "Read Flash Contents from Node ..."
#define STR_TEXT_DFM_XM_FLASHLOCALID_ESX  "Flash Node"
#define STR_TEXT_DFM_XM_WAKEUPLOCALID_BBB "Wakeup ESX + BBB"
#define STR_TEXT_DFM_XM_READ_FROM_ESX_BBB "Read from BBB to File"
#define STR_TEXT_DFM_XM_FLASHLOCALID_BBB  "Flash BBB"
#define STR_TEXT_DFM_XM_CAP_HEXFILE       "Hex File:"
#define STR_TEXT_DFM_XM_C_APPLICATION     "C application (all sectors)"
#define STR_TEXT_DFM_XM_CANOPEN_CONFIG    "CANopen configuration"
#define STR_TEXT_DFM_XM_IEC_APPLICATION   "IEC1131 application"
#define STR_TEXT_DFM_XM_IEC_RTS           "IEC1131 run-time-system"
#define STR_TEXT_DFM_XM_USER_DEFINED      "User defined"
#define STR_TEXT_DFM_XM_BBB_APPLICATION   "BBB application"
#define STR_TEXT_DFM_XM_BBB_PARAMETERS    "BBB parameters"

#define STR_TEXT_DFM_XM_CAPTION    "Winflash ++ [no config loaded]"
#define STR_TEXT_DFM_XM_CANDLL     "Comm-DLL:"
#define STR_TEXT_DFM_XM_SELECT     "Select"
#define STR_TEXT_DFM_XM_VIEW       "View"
#define STR_TEXT_DFM_XM_STARTTIME  "Start Time:"
#define STR_TEXT_DFM_XM_DELAY      "Delay:"
#define STR_TEXT_DFM_XM_CONFIG     "Configuration:"
#define STR_TEXT_DFM_XM_DELAY_HINT "Delay in us between individual TX messages"
#define STR_TEXT_DFM_XM_STIME_HINT "Determines how long Winflash will send the 'Ping' to the target node(s)"
#define STR_TEXT_DFM_XM_EXIT       "Exit"
#define STR_TEXT_DFM_XM_SEARCH     "Search Nodes"
#define STR_TEXT_DFM_XM_TRIM       "Sort Hex File ..."
#define STR_TEXT_DFM_XM_WAKEUP_SNR "Configure Node (Address by Serial Number)"
//#define STR_TEXT_DFM_XM_SW_BIN     "SW Bin Download"
//#define STR_TEXT_DFM_XM_SW_HEX     "SW Hex Download"
#define STR_TEXT_DFM_XM_FPARAMS    "Flash Parameters"
#define STR_TEXT_DFM_XM_SENDID     "Send ID:"
#define STR_TEXT_DFM_XM_CID        "Company ID:"
#define STR_TEXT_DFM_XM_LID        "Local ID:"
#define STR_TEXT_DFM_XM_SNR        "Node's Serial Number:"
#define STR_TEXT_DFM_XM_BR         "Bitrate:"
//#define STR_TEXT_DFM_XM_SW_BIN_ID  "Bin DL TX ID:"
//#define STR_TEXT_DFM_XM_SW_HEX_ID  "Hex DL TX ID:"
#define STR_TEXT_DFM_XM_SEND_ID_HINT "CAN identifier for the message (decimal or with 0x-prefix)"
#define STR_TEXT_DFM_XM_CID_HINT   "Company ID (2 or 3 characters)"
#define STR_TEXT_DFM_XM_LID_HINT   "Local ID of the server to flash (decimal or with 0x-prefix; 0..254)"
#define STR_TEXT_DFM_XM_FILETYPE   "Type of Hex File"
#define STR_TEXT_DFM_XM_SECTORS    "Sectors:"
#define STR_TEXT_DFM_XM_RESET_RQ   "Reset Request"
#define STR_TEXT_DFM_XM_RESET_MSG_HINT "Reset Message (decimal)"
#define STR_TEXT_DFM_XM_RESET_MSG_MSG  "Message:"
#define STR_TEXT_DFM_XM_RESET_MSG_SEND "Send Reset RQ"
#define STR_TEXT_DFM_XM_RESET_MSG_CFG  "Configure"
//#define STR_TEXT_DFM_XM_DEBUG          "DEBUG Interface Setup"
#define STR_TEXT_DFM_XM_FILTER_HEXFILES "Intel Hex files (*.HEX)|*.HEX|All files (*.*)|*.*"
#define STR_TEXT_DFM_XM_FILTER_CANDLLS  "DLLs (*.DLL)|*.DLL"
#define STR_TEXT_DFM_XM_FILTER_HEXFILE  "Hexfile (*.HEX)|*.HEX"
#define STR_TEXT_DFM_XM_HEXFILE_SELECT  "Select Hex File ..."
#define STR_TEXT_DFM_XM_DLL_SELECT      "Select Communication Driver DLL ..."
#define STR_TEXT_DFM_XM_SAVE_CONFIG     "Save Current Configuration ..."
#define STR_TEXT_DFM_XM_MENU_ACTIONS    "&Actions"
#define STR_TEXT_DFM_XM_VERIFY          "Verify Flash Contents on Node"
#define STR_TEXT_DFM_XM_FLASH_SNR       "Flash Node (Address by Serial Number)"
#define STR_TEXT_DFM_XM_TARGET          "&Target"
#define STR_TEXT_DFM_XM_MAINBOARD       "&Mainboard"
#define STR_TEXT_DFM_XM_BBB             "&ESX2 BBB"

//DlgKFXEditPasswords/DlgKFXPasswords
#define STR_TEXT_DFM_EP_CAPTION         "Edit Passwords"
#define STR_TEXT_DFM_EP_PASSWORD        "Password:"
#define STR_TEXT_DFM_EP_CONFIRM         "Confirm:"
#define STR_TEXT_DFM_EP_GROUP           "Group:"
#define STR_TEXT_DFM_EP_CB_GROUP0       "Group 0"
#define STR_TEXT_DFM_EP_CB_GROUP1       "Group 1"
#define STR_TEXT_DFM_EP_CB_GROUP2       "Group 2"
#define STR_TEXT_DFM_EP_CB_GROUP3       "Group 3"
#define STR_TEXT_DFM_EP_CB_GROUP4       "Group 4"
#define STR_TEXT_DFM_EP_CB_GROUP5       "Group 5"
#define STR_TEXT_DFM_EP_CB_GROUP6       "Group 6"
#define STR_TEXT_DFM_EP_CB_GROUP7       "Group 7"
#define STR_TEXT_DFM_EP_CB_GROUP8       "Group 8"
#define STR_TEXT_DFM_EP_CB_GROUP9       "Group 9"
#define STR_TEXT_DFM_EP_CB_PROGRAMMER   "Programmer"
#define STR_TEXT_DFM_EP_APPLY           "Apply"
#define STR_TEXT_DFM_PWD_CAPTION        "Access Control"
#define STR_TEXT_DFM_PWD_GB_CAPTION     "Select User Group And Enter Password"

//DlgKFXIndexedInputListEditor
#define STR_TEXT_DFM_IILE_CAPTION       "Indexed BMP input list editor"
#define STR_TEXT_DFM_IILE_NEW           "New"
#define STR_TEXT_DFM_IILE_DELETE        "Delete"
#define STR_TEXT_DFM_IILE_HELP1         "Click on a cell in the column 'FileName' to select the desired file."
#define STR_TEXT_DFM_IILE_HELP2         "Enter the value in the column 'Value'."
#define STR_TEXT_DFM_IILE_FILTER_BMPS   "Bitmaps (*.bmp)|*.bmp"

//DlgKFXIndexedListEditor
#define STR_TEXT_DFM_ILE_CAPTION        "Indexed filename list editor"
#define STR_TEXT_DFM_ILE_HELP1          "Click on a cell in the column 'FileName' to select the desired file"
#define STR_TEXT_DFM_ILE_HELP2          "Enter the value in the column 'Value Range'."
#define STR_TEXT_DFM_ILE_HELP3          "Possible formats:"
#define STR_TEXT_DFM_ILE_HELP4          "- single value (e.g. '125')"
#define STR_TEXT_DFM_ILE_HELP5          "- value range (e.g. '1..25');"

//DlgKFXIndexedStringEditor
#define STR_TEXT_DFM_ISE_CAPTION        "Indexed stringlist editor"
#define STR_TEXT_DFM_ISE_HELP1          "Click on a cell in the column 'String' to enter the desired text."
#define STR_TEXT_DFM_ISE_HELP2          "Enter the value in the column 'Value'."

//DlgXFLWakeup
#define STR_TEXT_DFM_XW_CAPTION         "Wakeup ..."
#define STR_TEXT_DFM_XW_CONFIG          "Flash Configuration"
#define STR_TEXT_DFM_XW_SLEEP           "Sleep"
#define STR_TEXT_DFM_XW_RETURN          "Return"
#define STR_TEXT_DFM_XW_RESET           "Reset"
#define STR_TEXT_DFM_XW_SET             "Set"
#define STR_TEXT_DFM_XW_FLASH_CRCS      "Flash CRCs"
//#define STR_TEXT_DFM_XW_CMP             "CMP  Block Nr / Calc CRC / CRC in EE / Start Add / End Add"
//#define STR_TEXT_DFM_XW_SET_CRC         "Set CRC"
#define STR_TEXT_DFM_XW_GET_CRCS        "Get CRCs"
#define STR_TEXT_DFM_XW_TO_FACTORS      "Timeout Factors for SM-Module"
#define STR_TEXT_DFM_XW_TO_FACTOR_ERASE "Erase Timeout Factor (%):"
#define STR_TEXT_DFM_XW_TO_FACTOR_WRITE "Write Timeout Factor (%):"
#define STR_TEXT_DFM_XW_TO_ERASE_HINT \
   "If using ESX with SMM module, the ESX will wait this time for the SMM flash to finish it's erase operation."
#define STR_TEXT_DFM_XW_TO_WRITE_HINT \
   "If using ESX with SMM module, the ESX will wait this time for the SMM flash to finish it's write operation."
#define STR_TEXT_DFM_XW_INFORMATION     "Information"
#define STR_TEXT_DFM_XW_BBBINFO         "BBBInfo"
#define STR_TEXT_DFM_XW_LAST_FLASHED    "Last flashed by:"

//DlgXFLSearch
#define STR_TEXT_DFM_XS_CAPTION         "Results:"
#define STR_TEXT_DFM_XS_NODE_IDS        "Found nodes:"
//#define STR_TEXT_DFM_XS_SNRS            "SNRs:"
#define STR_TEXT_DFM_XS_CHANGEID        "Change ID"

//DlgXFLBBBDivertStream
#define STR_TEXT_DFM_XBB_CAPTION      "BBB Config"
#define STR_TEXT_DFM_XBB_SETTINGS     "Settings for Divert Stream"
#define STR_TEXT_DFM_XBB_SLOT         "BBB Slot:"
#define STR_TEXT_DFM_XBB_PASSWORD     "Password:"

//DlgRVChart
#define STR_TEXT_DFM_RVC_CAPTION       "KEFEX RAMView Graph"
#define STR_TEXT_DFM_RVC_XAXIS_CAPTION "Time (ms)"
#define STR_TEXT_DFM_RVC_HELP1         "Options when there is no active trace:"
#define STR_TEXT_DFM_RVC_HELP2         ""
#define STR_TEXT_DFM_RVC_HELP3         "Zoom In:"
#define STR_TEXT_DFM_RVC_HELP4 \
   "-> While holding the right mouse button draw a rectangle around the area you wish to view starting from the upper left."
#define STR_TEXT_DFM_RVC_HELP5         ""
#define STR_TEXT_DFM_RVC_HELP6         "Zoom Out:"
#define STR_TEXT_DFM_RVC_HELP7 \
   "-> While holding the right mouse button draw a rectangle starting from the lower right."
#define STR_TEXT_DFM_RVC_HELP8         ""
#define STR_TEXT_DFM_RVC_HELP9         "Pan:"
#define STR_TEXT_DFM_RVC_HELP10        "-> Hold down the right mouse button and move cursor."
#define STR_TEXT_DFM_RVC_HELP11        ""
#define STR_TEXT_DFM_RVC_HELP12        "Show Value:"
#define STR_TEXT_DFM_RVC_HELP13 \
   "-> Move the mouse cursor over a point in the diagram. The values corresponding to that point will be shown in the status bar. This is only possible if no cursors are set."
#define STR_TEXT_DFM_RVC_HELP14        ""
#define STR_TEXT_DFM_RVC_HELP15        "Cursor Mode:"
#define STR_TEXT_DFM_RVC_HELP16 \
   "-> You can set two cursors for displaying numeric values. Click the left mouse button on a point in the diagram to set the first (= reference) cursor. The right mouse button sets the second cursor."
#define STR_TEXT_DFM_RVC_HELP17 \
   "-> Now you can use the arrow and double arrow buttons to browse through the diagram (or you can use PGUP/PGDOWN with or without SHIFT)."
#define STR_TEXT_DFM_RVC_HELP18        "-> The values of all variables will be displayed."
#define STR_TEXT_DFM_RVC_HELP19 \
   "-> There are two different methods for calculation of differences. You can switch between the two with the checkbox 'Reference mode'."
#define STR_TEXT_DFM_RVC_HELP20 \
   "-> To remove the cursors do a (short) click on a point which is not near a line with the left (cursor 1) or right (cursor 2) mouse buttons."
#define STR_TEXT_DFM_RVC_HELP21        ""
#define STR_TEXT_DFM_RVC_HELP22        "'Reference mode' disabled:"
#define STR_TEXT_DFM_RVC_HELP23 \
   "Value and timestamp differences will refer to their differences on both intersections between the cursor line and the value curves."
#define STR_TEXT_DFM_RVC_HELP24        ""
#define STR_TEXT_DFM_RVC_HELP25        "'Reference mode' enabled:"
#define STR_TEXT_DFM_RVC_HELP26 \
   "Value and timestamp differences will refer to exactly one point (= the first cursor). This can be on any of the six values curves (change with the left mouse button)."
#define STR_TEXT_DFM_RVC_HELP27        ""
#define STR_TEXT_DFM_RVC_HELP28        ""
#define STR_TEXT_DFM_RVC_HELP29        ""
#define STR_TEXT_DFM_RVC_HELP30        ""
#define STR_TEXT_DFM_RVC_NTV           "Name/Time/Value"
#define STR_TEXT_DFM_RVC_SELECTED      "Selected value:"
#define STR_TEXT_DFM_RVC_VARIABLE      "Variable:"
#define STR_TEXT_DFM_RVC_TIMESTAMP     "Timestamp:"
#define STR_TEXT_DFM_RVC_VALUE         "Value:"
#define STR_TEXT_DFM_RVC_VISIBLE       "Visible Points:"
#define STR_TEXT_DFM_RVC_INTERVAL      "Interval (ms):"
#define STR_TEXT_DFM_RVC_CB_DISPLAY    "Display values"
#define STR_TEXT_DFM_RVC_CB_S1         "Series 1"
#define STR_TEXT_DFM_RVC_CB_S2         "Series 2"
#define STR_TEXT_DFM_RVC_CB_S3         "Series 3"
#define STR_TEXT_DFM_RVC_CB_S4         "Series 4"
#define STR_TEXT_DFM_RVC_CB_S5         "Series 5"
#define STR_TEXT_DFM_RVC_CB_S6         "Series 6"
#define STR_TEXT_DFM_RVC_ALL           "All"
#define STR_TEXT_DFM_RVC_SHOW_MARKERS  "Show markers"
#define STR_TEXT_DFM_RVC_CURSORS       "Cursors"
#define STR_TEXT_DFM_RVC_BLACK         "Black"
#define STR_TEXT_DFM_RVC_GREY          "Grey"
#define STR_TEXT_DFM_RVC_REFERENCE     "Reference mode"
#define STR_TEXT_DFM_RVC_STATUS        "Status:"
#define STR_TEXT_DFM_RVC_START_HINT    "Start trace"
#define STR_TEXT_DFM_RVC_START_CAPTION "Start"
#define STR_TEXT_DFM_RVC_START_TS_HINT "Start trace with timestamps"
#define STR_TEXT_DFM_RVC_START_TS_CAPTION "Start (TS)"
#define STR_TEXT_DFM_RVC_STOP_HINT     "Stop trace"
#define STR_TEXT_DFM_RVC_STOP_CAPTION  "Stop"
#define STR_TEXT_DFM_RVC_CLEAR_HINT    "Clear trace"
#define STR_TEXT_DFM_RVC_CLEAR_CAPTION "Clear List"
#define STR_TEXT_DFM_RVC_SAVE_HINT     "Save buffer to file"
#define STR_TEXT_DFM_RVC_SAVE_CAPTION  "Save"
#define STR_TEXT_DFM_RVC_LOAD_HINT     "Load from buffer file"
#define STR_TEXT_DFM_RVC_LOAD_CAPTION  "Load"
#define STR_TEXT_DFM_RVC_PRINT_HINT    "Print chart"
#define STR_TEXT_DFM_RVC_PRINT_CAPTION "Print"
#define STR_TEXT_DFM_RVC_CLIP_HINT     "Copy chart to clipboard as bitmap"
#define STR_TEXT_DFM_RVC_CLIP_CAPTION  "Copy"
#define STR_TEXT_DFM_RVC_RCH_FILTER    "RAMView Chart Files (*.RCH)|*.RCH"

//DlgXFLFinished
#define STR_TEXT_DFM_XFF_CAPTION        "Flashing finished ..."
#define STR_TEXT_DFM_XFF_RG_CAPTION     "Please select"
#define STR_TEXT_DFM_XFF_RG_ITEM1       "Start program"
#define STR_TEXT_DFM_XFF_RG_ITEM2       "Start all nodes"
#define STR_TEXT_DFM_XFF_RG_ITEM3       "Do not start (stay in sleep mode)"

//new strings added after V1.0
#define STR_TEXT_KFX_ERR_OPEN_KSP_FILE   "Could not open KSP project file."

#define STR_TEXT_KSP_ALREADY_EXISTS      "The specified KSP file already exists. Overwrite exisiting file ?"
#define STR_TEXT_DS_ERR_ADDRESS_RESPONSE "Invalid response: wrong address."
#define STR_TEXT_FW_ERR_ID_TYPE_NOCHANGE "Could not change ID type."
#define STR_TEXT_FW_ID_TYPE_CHANGED      "ID type changed."
#define STR_TEXT_FW_ERR_NO_XTD           "PC CAN hardware cannot handle 29Bit IDs."
#define STR_TEXT_FW_ERR_NO_XTD_CONTINUE \
   "PC CAN hardware cannot handle 29Bit IDs. Are you sure to change this setting ?"
#define STR_TEXT_FW_INFO_RESET           "Change will take affect after reset."
#define STR_TEXT_DS_ERR_TRANSFER         "Error with segmented transfer."
#define STR_TEXT_CM_ERR_INI_WRITE \
   "Could not write CMON.INI (possibly write protected). Configuration will not be saved."
#define STR_TEXT_DS_ERR_INI_WRITE \
   "Could not write to file (possibly write protected). Configuration was not saved."
#define STR_TEXT_DS_ERR_PROJECT_INVALID \
   "Error opening project: Make sure that only files used by this project are in the directory."
#define STR_TEXT_DFM_CS_COMMENT_CAP      "Comment:"

#define STR_TEXT_KSP_READ_ACCESS_DENIED   "Read access is denied by the KSP project file."
#define STR_TEXT_KSP_WRITE_ACCESS_DENIED  "Write access is denied by the KSP project file."

#define STR_TEXT_VERSION_CHECK "1.0"

#endif
